version: '3.9'
services:
  trooper-ms-payment:
    container_name: ms-payment
    build: ./
    ports:
      - 3001:3001
    volumes:
      - ./:/app/ms-payment
    environment:
      - PORT=3001
      - DB_HOST=mongodb-ms-payment
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=ms-payment
      - JWT_SECRET=MTk4OGExOTZkMWYyOWZjZjlmOTcwMWVjZWRjMzc1MzZkOGM0MmFjMjQ0NjcyZjIzZDQwOGU4YTQ1YWQ3NTRjZA==
    depends_on:
      - mongodb-ms-payment

  mongodb-ms-payment:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - mongodb-payment-volume-docker:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret

  mongodb-ms-payment-test:
    image: mongo:5
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  mongodb-payment-volume-docker: